version: "3.6"
services:
  nginx:
    image: nginx:1.15
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./portfolio:/var/www/html/portfolio
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

  node:
    ports:
      - "24678:24678"
    user: root
    build:
      dockerfile: Dockerfile
      context: ./config/portfolio
    working_dir: /var/www/html/portfolio
    volumes:
      - ./portfolio:/var/www/html/portfolio
    command: sh -c "node .output/server/index.mjs"
    stdin_open: true
    tty: true
    networks:
      - default

networks:
  portfolio:
    driver: bridge
