version: "3.6"
services:
  nginx:
    image: nginx:1.15
    working_dir: /var/www/html
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./portfolio:/var/www/html/portfolio
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    networks:
      - portfolio

  node:
    build:
        dockerfile: Dockerfile
        context: ./config/portfolio
    ports:
      - "24678:24678"
    user: node
    container_name: node
    working_dir: /var/www/html/portfolio
    volumes:
      - ./portfolio:/var/www/html/portfolio
    command: sh -c "node .output/server/index.mjs"
    stdin_open: true
    tty: true
    networks:
      - portfolio

networks:
  portfolio:
    driver: bridge
